//Dave A. Berque, Revised August 2011
//This file contains some general constant definitions that are likely to
//be useful in several parts of the compiler.  Feel free to add
//additional definitions here.

#ifndef _general
#define _general

const int MAXCELLSPERSTRING = 82;  //80 characters plus \n plus \0.

/*const int ASSIGN_T = 1;
const int RELOP_T = 2;
const int ADDOP_T = 3;
const int MULOP_T = 4;
const int SEMICOL_T = 5;
const int IDENT_T = 6;
const int INT_T = 7;
const int STRING_T = 8;
const int PAREN_T = 9;
const int COMMA_T = 10;
const int AMPERS_T = 11;
const int PERIOD_T = 12;
const int EOF_T = 13;
const int EQUALS_ST = 24;
const int EQUEQU_ST = 25;
const int GRTH_ST = 26;
const int GREQ_ST = 27;
const int NTEQ_ST = 28;
const int LSTH_ST = 29;
const int LSEQ_ST = 30;
const int SWAP_ST = 31;
const int STREXT_ST = 32;
const int STRINS_ST = 33;
const int MINUS_ST = 34;
const int PLUS_ST = 35;
const int MULT_ST = 36;
const int LEFTPAR_ST = 37;
const int RIGHTPAR_ST = 38;*/

#endif